version: 2

parameters:
  BUILDER_IMAGE: "docker.tuenti.io/android/mistica_builder:1"

defaults:
  platform: "docker-large"

  plugins:
    mail:
      enabled: true
      recipients:

timeout: 60
workflows:
  deploy:
    stages: ["docker_up", "deploy", "docker_down"]
    plugins:
      vault:
        secrets:
          - path: secret/services/jenkins/maven-private
            keys:
              username: NEXUS_USER
              password: NEXUS_PASS
  publish:
    stages: ["docker_up", "deploy_and_catalog", "docker_down"]
    plugins:
      vault:
        secrets:
          - path: secret/services/jenkins/maven-private
            keys:
              username: NEXUS_USER
              password: NEXUS_PASS
              appcenter_project_key: APPCENTER_KEY
              appcenter_api_token: APPCENTER_API_TOKEN
  image:
    stages: ["build_image", "push_image"]

stages:
  docker_up:
    - "docker-compose pull"
    - "docker-compose up -d builder"
  deploy:
    - "docker-compose exec -T builder bash -c \"cd /source; ./gradlew clean check assemble; ./gradlew publish\""
  deploy_and_catalog:
    - "docker-compose exec -T builder bash -c \"cd /source; ./gradlew clean check assemble; ./gradlew publish; ./gradlew appCenterAssembleAndUploadDebug\""
  docker_down:
    - "docker-compose down -v"
  build_image:
    - "docker build -t ${BUILDER_IMAGE} ."
  push_image:
    - "docker push ${BUILDER_IMAGE}"
