version: 2
 
parameters:
 BUILDER_IMAGE: "docker.tuenti.io/android/mistica_builder:1"
 
defaults:
 platform: "docker-large"
 
 plugins:
     mail:
       enabled: true
       recipients:
 
timeout: 60
workflows:
 deploy:
   stages: ["docker_up", "deploy", "docker_down"]
   plugins:
     vault:
       secrets:
         - path: secret/services/jenkins/maven-private
           keys:
             username: NEXUS_USER
             password: NEXUS_PASS
 image:
   stages: ["build_image", "push_image"]
 
stages:
 docker_up:
   - "docker-compose pull"
   - "docker-compose up -d builder"
 deploy:
   - "docker-compose exec -T builder bash -c \"cd /source; ./gradlew check assemble; ./gradlew publish\""
 docker_down:
   - "docker-compose down -v"
 build_image:
   - "docker build -t ${BUILDER_IMAGE} ."
 push_image:
   - "docker push ${BUILDER_IMAGE}"
