version: '2'

services:
  builder:
    image: "${BUILDER_IMAGE}"
    command: "bash -c 'adb start-server; sleep infinity'"
    environment:
      TERM: "xterm" # Needed for gradle
      NEXUS_USER: "${NEXUS_USER}"
      NEXUS_PASS: "${NEXUS_PASS}"
      APPCENTER_KEY: "${APPCENTER_KEY}"
      APPCENTER_API_TOKEN: "${APPCENTER_API_TOKEN}"
    volumes:
      - ".:/source"
      - "/var/lib/gradle-cache:/root/.gradle"
      - "/var/lib/maven-cache:/root/.m2"
      - "/var/lib/gradle-build-cache:/root/.android/build-cache/"
