package com.telefonica.mistica.tokens.xml

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.telefonica.mistica.tokens.TokensGenerator
import java.io.File

/**
 * Generates the `MisticaGradientAutogenerated.kt` file, which is an enum with all available xml gradients in Mistica.
 */
class GenerateMisticaGradients {

    operator fun invoke(gradientTokensNames: List<String>) {
        val gradientsEnum = TypeSpec.enumBuilder(MISTICA_GRADIENT)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameters(getConstructorParameters())
                    .build()
            )
            .addProperties(getProperties())
            .apply {
                gradientTokensNames.forEach { tokenName ->
                    addEnumConstant(tokenName.capitalizeString(), getEnumParams(tokenName))
                }
            }
            .build()

        val file = FileSpec.builder("com.telefonica.mistica.theme.color", "${MISTICA_GRADIENT}Autogenerated")
            .addFileComment(TokensGenerator.AUTOGENERATED_COMMENT)
            .addType(gradientsEnum)
            .build()

        file.writeTo(File(LIBRARY_CODE_PATH))
    }

    private fun getConstructorParameters(): List<ParameterSpec> =
        listOf(
            ParameterSpec.builder(
                GRADIENT_COLORS_PROPERTY_NAME,
                intClass
            ).addAnnotation(attrResClass).build(),
            ParameterSpec.builder(
                GRADIENT_STOPS_PROPERTY_NAME,
                intClass
            ).addAnnotation(attrResClass).build(),
            ParameterSpec.builder(
                GRADIENT_ANGLE_PROPERTY_NAME,
                intClass
            ).addAnnotation(attrResClass).build()
        )

    private fun getProperties(): List<PropertySpec> =
        listOf(
            PropertySpec.builder(
                GRADIENT_COLORS_PROPERTY_NAME,
                intClass
            ).initializer(GRADIENT_COLORS_PROPERTY_NAME).build(),
            PropertySpec.builder(
                GRADIENT_STOPS_PROPERTY_NAME,
                intClass
            ).initializer(GRADIENT_STOPS_PROPERTY_NAME).build(),
            PropertySpec.builder(
                GRADIENT_ANGLE_PROPERTY_NAME,
                intClass
            ).initializer(GRADIENT_ANGLE_PROPERTY_NAME).build()
        )

    private fun getEnumParams(tokenName: String): TypeSpec =
        TypeSpec
            .anonymousClassBuilder()
            .addSuperclassConstructorParameter("%T.attr.%L", rClass, "$BRAND_GRADIENT_COLORS_ATTR_PREFIX${tokenName.capitalizeString()}")
            .addSuperclassConstructorParameter("%T.attr.%L", rClass, "$BRAND_GRADIENT_STOPS_ATTR_PREFIX${tokenName.capitalizeString()}")
            .addSuperclassConstructorParameter("%T.attr.%L", rClass, "$BRAND_GRADIENT_ANGLE_ATTR_PREFIX${tokenName.capitalizeString()}")
            .build()

    companion object {
        const val BRAND_GRADIENT_COLORS_ATTR_PREFIX = "gradientColors"
        const val BRAND_GRADIENT_STOPS_ATTR_PREFIX = "gradientStops"
        const val BRAND_GRADIENT_ANGLE_ATTR_PREFIX = "gradientAngle"

        private const val LIBRARY_CODE_PATH = "../library/src/main/java/"

        private const val MISTICA_GRADIENT = "MisticaGradient"

        private const val GRADIENT_COLORS_PROPERTY_NAME = "gradientColorsAttrRes"
        private const val GRADIENT_STOPS_PROPERTY_NAME = "gradientStopsAttrRes"
        private const val GRADIENT_ANGLE_PROPERTY_NAME = "gradientAngleAttrRes"

        private val intClass = ClassName("kotlin", "Int")
        private val rClass = ClassName("com.telefonica.mistica", "R")
        private val attrResClass = ClassName("androidx.annotation", "AttrRes")

        fun String.capitalizeString(): String =
            this.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
    }
}