package com.telefonica.mistica.tokens.xml

import com.squareup.moshi.JsonAdapter
import com.telefonica.mistica.tokens.TokensGenerator.Companion.AUTOGENERATED_COMMENT
import com.telefonica.mistica.tokens.TokensGenerator.Companion.MISTICA_TOKENS_DIR
import com.telefonica.mistica.tokens.dto.TokensDTO
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.ATTRS_FILE
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.VALUES_DIR
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.capitalizeString
import org.redundent.kotlin.xml.Node
import org.redundent.kotlin.xml.XmlVersion
import org.redundent.kotlin.xml.xml
import java.io.File

class GenerateAttributesFile {

    operator fun invoke(jsonAdapter: JsonAdapter<TokensDTO>) {
        val json = File("${MISTICA_TOKENS_DIR}/movistar.json").readText()
        val tokens = jsonAdapter.fromJson(json)

        if (tokens == null) {
            throw Exception("Invalid JSON")
        } else {
            val attributesXml = xml("resources", "utf-8", XmlVersion.V10) {
                comment(AUTOGENERATED_COMMENT)
                "declare-styleable" {
                    getColorAttributes(tokens)
                }

                "declare-styleable" {
                    getBorderRadiusAttributes(tokens)
                }
            }

            File("${VALUES_DIR}/${ATTRS_FILE}").writeText(attributesXml.toString())
        }
    }

    private fun Node.getColorAttributes(tokens: TokensDTO) {
        attribute("name", "Colors")
        tokens.light.forEach { color ->
            var key = color.key

            if (key == "controlActivated") {
                comment("We cannot use colorControlActivated in Android because it overlaps with a framework attribute")
                key = "controlActive"
            }

            "attr" {
                getColorElement("color${key.capitalizeString()}")
            }
        }

        GRADIENT_ATTRS.forEach { color ->
            "attr" {
                getColorElement(color)
            }
        }
    }

    private fun Node.getColorElement(colorName: String) {
        attribute("name", colorName)
        attribute("format", "color|reference")
    }

    private fun Node.getBorderRadiusAttributes(tokens: TokensDTO) {
        attribute("name", "BorderRadius")
        tokens.radius.forEach { (key, _) ->
            "attr" {
                attribute("name", "${key}BorderRadius")
                attribute("format", "dimension|fraction")
            }
        }
    }

    private companion object {
        val GRADIENT_ATTRS = listOf(
            "colorGradientBackgroundFirst",
            "colorGradientBackgroundSecond",
            "colorGradientBackgroundThird",
            "colorGradientBackgroundFourth",
            "colorLoginLoadingGradientFirst",
            "colorLoginLoadingGradientSecond",
            "colorLoginLoadingGradientThird",
            "colorLoginLoadingGradientFourth",
        )
    }
}