package com.telefonica.mistica.tokens.xml

import com.squareup.moshi.JsonAdapter
import com.telefonica.mistica.tokens.TokensGenerator.Companion.AUTOGENERATED_COMMENT
import com.telefonica.mistica.tokens.TokensGenerator.Companion.MISTICA_TOKENS_DIR
import com.telefonica.mistica.tokens.common.GetBorderRadiusName
import com.telefonica.mistica.tokens.dto.TokensDTO
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.ATTRS_FILE
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.FONT_SUFFIX
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.TEXT_SIZE_SUFFIX
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.TEXT_STYLE_SUFFIX
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.VALUES_DIR
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.capitalizeString
import org.redundent.kotlin.xml.Node
import org.redundent.kotlin.xml.XmlVersion
import org.redundent.kotlin.xml.xml
import java.io.File

/**
 * Generates the `attrs_autogenerated.xml` file, which contains all the tokens defined in Mistica.
 */
class GenerateAttributesFile(
    private val getBorderRadiusName: GetBorderRadiusName = GetBorderRadiusName(),
) {

    operator fun invoke(jsonAdapter: JsonAdapter<TokensDTO>) {
        val json = File("${MISTICA_TOKENS_DIR}/movistar.json").readText()
        val tokens = jsonAdapter.fromJson(json)

        if (tokens == null) {
            throw Exception("Invalid JSON")
        } else {
            val attributesXml = xml("resources", "utf-8", XmlVersion.V10) {
                comment(AUTOGENERATED_COMMENT)
                DECLARE_STYLEABLE {
                    getColorAttributes(tokens)
                }

                DECLARE_STYLEABLE {
                    getBorderRadiusAttributes(tokens)
                }

                DECLARE_STYLEABLE {
                    getPresetFontsAttributes(tokens)
                }

                DECLARE_STYLEABLE {
                    getPresetStylesAttributes(tokens)
                }

                DECLARE_STYLEABLE {
                    getPresetSizesAttributes(tokens)
                }
            }

            File("${VALUES_DIR}/${ATTRS_FILE}").writeText(attributesXml.toString())
        }
    }

    private fun Node.getColorAttributes(tokens: TokensDTO) {
        attribute("name", "Colors")
        tokens.light.forEach { color ->
            var key = color.key

            if (key == "controlActivated") {
                comment("We cannot use colorControlActivated in Android because it overlaps with a framework attribute")
                key = "controlActive"
            }

            ATTR {
                getColorElement("color${key.capitalizeString()}")
            }
        }

        GRADIENT_ATTRS.forEach { color ->
            ATTR {
                getColorElement(color)
            }
        }
    }

    private fun Node.getColorElement(colorName: String) {
        attribute("name", colorName)
        attribute("format", "color|reference")
    }

    private fun Node.getBorderRadiusAttributes(tokens: TokensDTO) {
        attribute("name", "BorderRadius")
        tokens.radius.forEach { (key, _) ->
            ATTR {
                attribute("name", getBorderRadiusName(key))
                attribute("format", "dimension|fraction")
            }
        }
    }

    private fun Node.getPresetFontsAttributes(tokens: TokensDTO) {
        attribute("name", "PresetFonts")
        tokens.text.weight.forEach { (key, _) ->
            ATTR {
                attribute("name", "$key$FONT_SUFFIX")
                attribute("format", "string")
            }
        }
    }

    private fun Node.getPresetStylesAttributes(tokens: TokensDTO) {
        attribute("name", "PresetStyles")
        comment(
            "Important:\n" +
                    "        These constants are the same as \"android:textStyle\" flag values\n" +
                    "        and they have been replicated for each type of preset because\n" +
                    "        it's not possible to reference the original values out of android:textStyle usage."
        )
        tokens.text.weight.forEach { (key, _) ->
            ATTR {
                attribute("name", "$key$TEXT_STYLE_SUFFIX")
                attribute("format", "reference")
                FLAG {
                    attribute("name", "normal")
                    attribute("value", "0")
                }
                FLAG {
                    attribute("name", "bold")
                    attribute("value", "1")
                }
                FLAG {
                    attribute("name", "italic")
                    attribute("value", "2")
                }
            }
        }
    }

    private fun Node.getPresetSizesAttributes(tokens: TokensDTO) {
        attribute("name", "PresetSizes")
        tokens.text.size.forEach { (key, _) ->
            ATTR {
                attribute("name", "$key$TEXT_SIZE_SUFFIX")
                attribute("format", "dimension")
            }
        }
    }

    private companion object {
        val GRADIENT_ATTRS = listOf(
            "colorGradientBackgroundFirst",
            "colorGradientBackgroundSecond",
            "colorGradientBackgroundThird",
            "colorGradientBackgroundFourth",
            "colorLoginLoadingGradientFirst",
            "colorLoginLoadingGradientSecond",
            "colorLoginLoadingGradientThird",
            "colorLoginLoadingGradientFourth",
        )
        const val DECLARE_STYLEABLE = "declare-styleable"
        const val FLAG = "flag"
        const val ATTR = "attr"
    }
}