package com.telefonica.mistica.tokens

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import com.telefonica.mistica.tokens.dto.TokensDTO

class GenerateTokens {

    fun invoke() {
        val moshi: Moshi = Moshi.Builder()
            .addLast(KotlinJsonAdapterFactory())
            .build()
        val jsonAdapter: JsonAdapter<TokensDTO> = moshi.adapter(TokensDTO::class.java)

        GenerateXML().invoke(jsonAdapter)
    }

    companion object {
        val BRANDS = listOf("blau", "movistar", "o2", "telefonica", "vivo")
        val ALPHA_REGEX = "0\\.\\d{1,2}".toRegex()
        const val AUTOGENERATED_COMMENT = "Code generated automatically, DO NOT EDIT manually"
        const val MISTICA_TOKENS_DIR = "../.github/mistica-design/tokens"
    }
}
