package com.telefonica.mistica.tokens

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import com.telefonica.mistica.tokens.compose.GenerateComposeFiles
import com.telefonica.mistica.tokens.dto.TokensDTO
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles

class TokensGenerator(
    private val generateXMLFiles: GenerateXMLFiles = GenerateXMLFiles(),
    private val generateComposeFiles: GenerateComposeFiles = GenerateComposeFiles(),
) {

    fun generate() {
        val moshi: Moshi = Moshi.Builder()
            .addLast(KotlinJsonAdapterFactory())
            .build()
        val jsonAdapter: JsonAdapter<TokensDTO> = moshi.adapter(TokensDTO::class.java)

        generateXMLFiles(jsonAdapter)
        generateComposeFiles(jsonAdapter)
    }

    companion object {
        const val BLAU = "blau"
        const val MOVISTAR = "movistar"
        const val O2 = "o2"
        const val TELEFONICA = "telefonica"
        const val VIVO = "vivo"
        const val VIVO_NEW = "vivoNew"

        val BRANDS = listOf(
            Brand(BLAU, "blau"),
            Brand(MOVISTAR, "movistar"),
            Brand(O2, "o2"),
            Brand(TELEFONICA, "telefonica"),
            Brand(VIVO, "vivo"),
            Brand(VIVO_NEW, "vivo-new")
        )

        val ALPHA_REGEX = "0\\.\\d{1,2}".toRegex()
        const val AUTOGENERATED_COMMENT = "Code generated automatically, DO NOT EDIT manually. Use Import design tokens GitHub Action."
        const val AUTOGENERATED_COMMENT_FOR_VIVO_NEW = "Important: Do NOT let this file to be style name and its parent overwritten. There is a issue merging this style with Vivo regular."
        const val MISTICA_TOKENS_DIR = "../temp/mistica-design/tokens"
        const val CIRCLE_RADIUS = "circle"
        const val LIGHT = "light"
        const val REGULAR = "regular"
        const val MEDIUM = "medium"
        const val BOLD = "bold"
    }
}
