package com.telefonica.mistica.tokens.common

class GetGradientDrawableResourceName {
    operator fun invoke(
        brandName: String,
        tokenName: String,
    ): String = "gradient_${brandName}_${tokenName}_autogenerated".lowercase()
}
