package com.telefonica.mistica.tokens.compose

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.moshi.JsonAdapter
import com.telefonica.mistica.tokens.GenerateTokens
import com.telefonica.mistica.tokens.GenerateTokens.Companion.BRANDS
import com.telefonica.mistica.tokens.GenerateTokens.Companion.MISTICA_TOKENS_DIR
import com.telefonica.mistica.tokens.common.GetColorsWithAlpha
import com.telefonica.mistica.tokens.dto.TokensDTO
import com.telefonica.mistica.tokens.xml.GenerateXML.Companion.capitalizeString
import java.io.File

class GenerateCompose {

    private val getColorsWithAlpha = GetColorsWithAlpha()
    private val colorClass = ClassName("androidx.compose.ui.graphics", "Color")

    operator fun invoke(jsonAdapter: JsonAdapter<TokensDTO>) {
        val json = File("$MISTICA_TOKENS_DIR/movistar.json").readText()
        val tokens = jsonAdapter.fromJson(json)

        if (tokens == null) {
            throw Exception("Invalid JSON")
        } else {
            GenerateMisticaColors().invoke(getColors(tokens))


            BRANDS.forEach { brand ->
                val colorsObject = TypeSpec.objectBuilder("${brand.capitalizeString()}BrandColors").build()

                val properties = getPaletteProperties(tokens, brand)

                val paletteObject = TypeSpec.objectBuilder("${brand.capitalizeString()}PaletteColor")
                    .addModifiers(KModifier.PRIVATE)
                    .addProperties(properties)
                    .build()

                val file = FileSpec.builder("com.telefonica.mistica.compose.theme.brand", "${brand.capitalizeString()}BrandColorsAutogenerated")
                    .addFileComment(GenerateTokens.AUTOGENERATED_COMMENT)
                    .addType(colorsObject)
                    .addType(paletteObject)
                    .build()

                file.writeTo(File(LIBRARY_CODE_PATH))
            }
        }
    }

    private fun getPaletteProperties(
        tokens: TokensDTO,
        brand: String,
    ): MutableList<PropertySpec> {
        val properties = mutableListOf<PropertySpec>()

        tokens.global.palette.forEach { color ->
            val colorName = "${brand}_color_${color.key}"

            val property = PropertySpec.builder(colorName, colorClass)
                .initializer("%T(%L)", colorClass, color.value.value.toHexColor())
                .build()
            properties.add(property)
        }

        getColorsWithAlpha(tokens, brand).forEach { colorWithAlpha ->
            val property = PropertySpec.builder(colorWithAlpha.first, colorClass)
                .initializer("%T(%L)", colorClass, colorWithAlpha.second.toHexColor())
                .build()
            properties.add(property)
        }
        return properties
    }

    private fun String.toHexColor(): String {
        if (this.length == 7) {
            return "0xFF${this.substring(1)}"
        }

        return "0x${this.substring(1)}"
    }

    private fun getColors(tokens: TokensDTO) = tokens.light.keys.toList() + GRADIENT_COLORS

    companion object {
        const val LIBRARY_CODE_PATH = "../library/src/main/java/"
        private val GRADIENT_COLORS = listOf(
            "gradientBackgroundFirst",
            "gradientBackgroundSecond",
            "gradientBackgroundThird",
            "gradientBackgroundFourth",
            "loginLoadingGradientFirst",
            "loginLoadingGradientSecond",
            "loginLoadingGradientThird",
            "loginLoadingGradientFourth",
        )
    }
}
