package com.telefonica.mistica.tokens.compose

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.moshi.JsonAdapter
import com.telefonica.mistica.tokens.TokensGenerator
import com.telefonica.mistica.tokens.TokensGenerator.Companion.BRANDS
import com.telefonica.mistica.tokens.TokensGenerator.Companion.MISTICA_TOKENS_DIR
import com.telefonica.mistica.tokens.dto.TokensDTO
import com.telefonica.mistica.tokens.xml.GenerateXMLFiles.Companion.capitalizeString
import java.io.File

class GenerateComposeFiles(
    private val generateMisticaColors: GenerateMisticaColors = GenerateMisticaColors(),
    private val generateBrandColors: GenerateBrandColors = GenerateBrandColors(),
    private val generateMisticaRadius: GenerateMisticaRadius = GenerateMisticaRadius(),
) {

    operator fun invoke(jsonAdapter: JsonAdapter<TokensDTO>) {
        generateMisticaColors(jsonAdapter)
        generateMisticaRadius(jsonAdapter)

        BRANDS.forEach { brand ->
            val json = File("${MISTICA_TOKENS_DIR}/$brand.json").readText()
            val tokens = jsonAdapter.fromJson(json)
            if (tokens == null) {
                throw Exception("Invalid JSON")
            } else {
                generateBrandColors(tokens, brand)

                var radiusConstructor = "MisticaRadius("
                tokens.radius.forEach { (key, radius) ->
                    val value = if (radius.value == "circle") {
                        50
                    } else "${radius.value}.dp"

                    radiusConstructor += "\n${key}BorderRadius = ${value},"
                }
                radiusConstructor += ")"

                val radiusProperty = PropertySpec.builder("radius", misticaRadiusClass)
                    .initializer(radiusConstructor)
                    .build()

                val radiusObject = TypeSpec.objectBuilder("${brand.capitalizeString()}BrandRadius")
                    .addProperty(radiusProperty)
                    .build()

                val file = FileSpec.builder("com.telefonica.mistica.compose.theme.brand", "${brand.capitalizeString()}BrandRadiusAutogenerated")
                    .addFileComment(TokensGenerator.AUTOGENERATED_COMMENT)
                    .addImport("androidx.compose.ui.unit", "dp")
                    .addType(radiusObject)
                    .build()

                file.writeTo(File(LIBRARY_CODE_PATH))
            }
        }
    }

    companion object {
        const val LIBRARY_CODE_PATH = "../library/src/main/java/"
        const val MISTICA_COLORS = "MisticaColors"
        val misticaColorsClass = ClassName("com.telefonica.mistica.compose.theme.color", MISTICA_COLORS)
        val colorClass = ClassName("androidx.compose.ui.graphics", "Color")
        val misticaRadiusClass = ClassName("com.telefonica.mistica.compose.theme.values", "MisticaRadius")
        val dpClass = ClassName("androidx.compose.ui.unit", "Dp")
        val intClass = ClassName("kotlin", "Int")
    }
}
