package com.telefonica.mistica.tokens.compose

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.moshi.JsonAdapter
import com.telefonica.mistica.tokens.TokensGenerator
import com.telefonica.mistica.tokens.compose.GenerateComposeFiles.Companion.dpClass
import com.telefonica.mistica.tokens.compose.GenerateComposeFiles.Companion.intClass
import com.telefonica.mistica.tokens.compose.GenerateComposeFiles.Companion.misticaRadiusClass
import com.telefonica.mistica.tokens.dto.RadiusDTO
import com.telefonica.mistica.tokens.dto.TokensDTO
import java.io.File

/**
 * Generates the `MisticaRadiusAutogenerated.kt` file, which contains all the radius defined in Mistica.
 */
class GenerateMisticaRadius {

    private val mutableStateOf = MemberName("androidx.compose.runtime", "mutableStateOf")
    private val structuralEqualityPolicy = MemberName("androidx.compose.runtime", "structuralEqualityPolicy")

    operator fun invoke(jsonAdapter: JsonAdapter<TokensDTO>) {
        val json = File("${TokensGenerator.MISTICA_TOKENS_DIR}/movistar.json").readText()
        val tokens = jsonAdapter.fromJson(json)

        if (tokens == null) {
            throw Exception("Invalid JSON")
        } else {
            val radiusClass = TypeSpec.classBuilder("MisticaRadius")
                .primaryConstructor(
                    FunSpec.constructorBuilder()
                        .addParameters(getConstructorParameters(tokens.radius))
                        .build()
                )
                .addProperties(getProperties(tokens.radius))
                .addFunction(getUpdateRadiusFunc(tokens.radius))
                .build()

            val file = FileSpec.builder("com.telefonica.mistica.compose.theme.values", "MisticaRadiusAutogenerated")
                .addImport("androidx.compose.runtime", "getValue")
                .addImport("androidx.compose.runtime", "setValue")
                .addFileComment(TokensGenerator.AUTOGENERATED_COMMENT)
                .addType(radiusClass)
                .addProperty(getLocalRadiusProperty())
                .build()

            file.writeTo(File(LIBRARY_CODE_PATH))
        }
    }

    private fun getLocalRadiusProperty(): PropertySpec {
        val providableCompositionLocalClass = ClassName("androidx.compose.runtime", "ProvidableCompositionLocal")
        val staticCompositionLocalOf = MemberName("androidx.compose.runtime", "staticCompositionLocalOf")
        return PropertySpec.builder("LocalMisticaRadius", providableCompositionLocalClass.parameterizedBy(misticaRadiusClass))
            .addModifiers(KModifier.INTERNAL)
            .initializer("%M { %T() }", staticCompositionLocalOf, misticaRadiusClass)
            .build()
    }

    private fun getProperties(radius: Map<String, RadiusDTO>): List<PropertySpec> =
        radius.map { (key, radius) ->
            val radiusName = getRadiusName(key)
            PropertySpec.builder(
                radiusName,
                getClassType(radius)
            )
                .mutable()
                .delegate("%M(%N, %M())", mutableStateOf, radiusName, structuralEqualityPolicy)
                .setter(
                    FunSpec.setterBuilder()
                        .addModifiers(KModifier.INTERNAL)
                        .build()
                )
                .build()
        }

    private fun getConstructorParameters(radius: Map<String, RadiusDTO>): List<ParameterSpec> =
        radius.map { (key, radius) ->
            val defaultValue = if (radius.value == "circle") {
                "0"
            } else {
                "Dp.Unspecified"
            }

            ParameterSpec.builder(
                getRadiusName(key),
                getClassType(radius)
            ).defaultValue(defaultValue).build()
        }

    private fun getClassType(radius: RadiusDTO): ClassName {
        val clazz = if (radius.value == "circle") {
            intClass
        } else {
            dpClass
        }
        return clazz
    }

    private fun getUpdateRadiusFunc(radius: Map<String, RadiusDTO>): FunSpec {
        val funSpec = FunSpec.builder("updateWith")
            .addParameter("other", misticaRadiusClass)

        radius.forEach { (key, _) ->
            val radiusName = getRadiusName(key)
            funSpec.addStatement("%N = other.%N", radiusName, radiusName)
        }

        return funSpec
            .build()
    }

    private fun getRadiusName(key: String): String = "${key}BorderRadius"

    private companion object {
        const val LIBRARY_CODE_PATH = "../library/src/main/java/"
    }
}
