name: "Generate catalog app"
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check pull request status
        if: "!github.event.pull_request.merged == true"
        run: 'echo "Skipping generation, pull request is not merged"'

      - name: Checkout repo
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v2

      - name: Publish catalog
        if: github.event.pull_request.merged == true
        env:
          APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
        run: 'bash ./gradlew clean check appCenterAssembleAndUploadDebug -Dappcenter_app_name=Mistica'

  firebase-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Telefonica/ios-github-workflows repo
        uses: actions/checkout@v4
        with:
          repository: Telefonica/android-shared-workflows
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .shared-workflows
          ref: firebase

      - name: Build and Upload to Firebase
        uses: ./.shared-workflows/.github/workflows/build-enterprise.yml
        with:
          build-tasks: 'assembleDebug'
          apk-path: '**/build/outputs/apk/debug/*.apk'
          additional-groups: 'mistica-internal-testers'
          distribution-track: 'internal'
          notify-ci-cd-publication: true
          notify-error-in-publication: true
