name: "Generate catalog app"
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  catalog:
    runs-on: self-hosted-novum
    steps:
    - name: Check pull request status
      if: "!github.event.pull_request.merged == true"
      run: 'echo "Skipping generation, pull request is not merged"'

    - name: Checkout repo
      if: github.event.pull_request.merged == true
      uses: actions/checkout@v2

    - name: Publish catalog
      if: github.event.pull_request.merged == true
      uses: docker://docker.tuenti.io/android/novum_android_api31:2
      env:
        APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
      with:
        args: 'bash ./gradlew clean check appCenterAssembleAndUploadDebug -Dappcenter_app_name=Mistica'
