name: "Generate main catalog app"
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  debug-firebase-catalog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read catalog version from properties file
        id: catalog_version
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './app/src/main/res/raw/config.properties'
          properties: 'APP_VERSION'

      - name: Firebase Publish
        uses: ./.github/actions/firebase-publish
        id: firebase-publish
        with:
          firebase-app-id: '1:771826505811:android:f64fec267b535d7f974ea6'
          firebase-json-file: ${{ secrets.FIREBASE_DIST_CREDENTIALS_NIGHTLY }}
          release-notes: 'Catalog for main branch version: ${{ steps.catalog_version.outputs.app_version }} - $(git log -1 --pretty=short)'
          app-icon: 'ic_launcher_internal'
          app-version: '${{ steps.catalog_version.outputs.app_version }}-${{ steps.short-sha.outputs.sha_short }}'

