name: Screenshot compare comment

on:
  pull_request:

jobs:
  Comment-CompareScreenshot:

    permissions:
      actions: read # for downloading artifacts
      contents: write # for pushing screenshot-diff to companion branch
      pull-requests: write # for creating a comment on pull requests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verify Screenshots (roborazzi)
        run: 'bash ./gradlew verifyRoborazziDebug'

      - id: check-if-there-are-compare-files
        if: always()
        name: Check if there are compare files
        shell: bash
        run: |
          # Find all the files ending with _compare.png
          files=$(find . -type f -name "*_compare.png" | grep "screenshots/")
          exist_compare_files="true"
          echo "exist_compare_files=$exist_compare_files" >> "$GITHUB_OUTPUT"
      - id: generate-diff-reports
        name: Generate diff reports
        if: steps.check-if-there-are-compare-files.outputs.exist_compare_files == 'true'
        env:
          BRANCH_NAME: companion_${{ github.event.workflow_run.head_branch }}
        shell: bash
        run: |
          # Find all the files ending with _compare.png in roborazzi folder
          files=$(find . -type f -name "*_compare.png" | grep "screenshots/")
          delimiter="$(openssl rand -hex 8)"
          {
            echo "reports<<${delimiter}"
          
            # Create markdown table header
            echo "Snapshot diff report"
            echo "| File name | Image |"
            echo "|-------|-------|"
          } >> "$GITHUB_OUTPUT"
          
          # Iterate over the files and create table rows
          for file in $files; do
            # Get the file name and insert newlines every 20 characters
            fileName=$(basename "$file" | sed -r 's/(.{20})/\1<br>/g')
            echo "| [$fileName](https://github.com/${{ github.repository }}/blob/$BRANCH_NAME/$file) | ![](https://github.com/${{ github.repository }}/blob/$BRANCH_NAME/$file?raw=true) |" >> "$GITHUB_OUTPUT"
          done
          echo "${delimiter}" >> "$GITHUB_OUTPUT"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        if: steps.generate-diff-reports.outputs.reports != ''
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Snapshot diff report

      - name: Add or update comment on PR
        uses: peter-evans/create-or-update-comment@v3
        if: steps.generate-diff-reports.outputs.reports != ''
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: ${{ steps.generate-diff-reports.outputs.reports }}
          edit-mode: replace
