name: "Promote draft release"
on:
  workflow_dispatch
jobs:
  promote:
    runs-on: self-hosted-novum
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Close and promote staging repository
        uses: docker://docker.tuenti.io/android/mistica_builder:2
        env:
          MOBILE_MAVENCENTRAL_USER: ${{ secrets.MOBILE_MAVENCENTRAL_USER }}
          MOBILE_MAVENCENTRAL_PASSWORD: ${{ secrets.MOBILE_MAVENCENTRAL_PASSWORD }}
        with:
          args: 'bash pwd && ./gradlew closeAndReleaseRepository -DSTAGING_PROFILE_ID="$(./gradlew getStagingProfile  | sed -n -e "s/^Received staging profile id: //p")"'

