name: "Publish library"
on:
  workflow_dispatch:
    inputs:
      libraryVersion:
        description: "Library version"
        required: true
      releaseDescription:
        description: "Release description"
        required: true
jobs:
  publish:
    runs-on: self-hosted-novum
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check permissions
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `check` step
      - name: Check permissions
        if: "! steps.check.outputs.has-permission"
        run: exit 1

      - name: Build library
        if: steps.check.outputs.has-permission
        uses: docker://docker.tuenti.io/android/mistica_builder:2
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        with:
          args: 'bash ./gradlew --no-daemon clean check assemble -DLIBRARY_VERSION=${{ github.event.inputs.libraryVersion }}'

      - name: Release library
        if: steps.check.outputs.has-permission
        uses: docker://docker.tuenti.io/android/mistica_builder:2
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        with:
          args: 'bash ./gradlew publish -DLIBRARY_VERSION=${{ github.event.inputs.libraryVersion }}'

      - name: Create Release in github
        if: steps.check.outputs.has-permission
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.libraryVersion }}
          release_name: ${{ github.event.inputs.libraryVersion }}
          body: ${{ github.event.inputs.releaseDescription }}
          draft: true
          prerelease: false
