name: "Publish library"
on: 
  workflow_dispatch:
    inputs:
      libraryVersion:
        description: "Library version"
        required: true
      releaseDescription:
        description: "Release description"
        required: true
jobs:
  publish:
    runs-on: self-hosted-novum
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref }}
          
      - name: Get the current branch name
        id: branch-name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        
      - run: 'echo -n ${{ github.event.inputs.libraryVersion }} > version.txt'
        shell: bash
          
      - name: Check permissions
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # Use the output from the `check` step
      - name: Check permissions
        if: "! steps.check.outputs.has-permission"
        run: exit 1    
        
      - name: Increase version
        uses: ./.github/actions/commit_and_push
        if: steps.check.outputs.has-permission
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release library
        if: steps.check.outputs.has-permission
        uses: satak/webrequest-action@master
        with:
          url: https://flow.tuenti.io/events/FLOW/SCRIPT_EVENT
          method: POST
          payload: '{"script": "tu-ci", "operation": "create_or_update_job",  "repository": "mistica-android",  "branch": "${{ steps.branch-name.outputs.branch }}",  "workflow": "publish",  "ticket": "APPS-7169", "username": "flow"}'

      - name: Create Release in github
        if: steps.check.outputs.has-permission
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.libraryVersion }}
          release_name: ${{ github.event.inputs.libraryVersion }}
          body: ${{ github.event.inputs.releaseDescription }}
          draft: true
          prerelease: false
