name: Generate catalog app
on: workflow_dispatch
jobs:
  release:
    runs-on: self-hosted-novum
    steps:
    - name: Release library
      uses: satak/webrequest-action@master
      with:
        url: https://flow.tuenti.io/events/FLOW/SCRIPT_EVENT
        method: POST
        payload: '{"script": "tu-ci", "operation": "create_or_update_job",  "repository": "mistica-android",  "branch": "master",  "workflow": "publish",  "ticket": "APPS-7169", "username": "flow"}'