name: "Upload release to MavenCentral"
on:
  release:
    types: [ published ]
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build library
        run: 'bash ./gradlew clean :library:assembleRelease :catalog:assembleRelease'

      - name: Release library
        env:
          MOBILE_MAVENCENTRAL_USER: ${{ secrets.MOBILE_MAVENCENTRAL_USER }}
          MOBILE_MAVENCENTRAL_PASSWORD: ${{ secrets.MOBILE_MAVENCENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
        run: "bash ./gradlew :library:publishReleasePublicationToSonatypeRepository -DLIBRARY_VERSION=${{ github.event.release.tag_name }}
         :catalog:publishCatalogPublicationToSonatypeRepository -DLIBRARY_VERSION=${{ github.event.release.tag_name }}
         --max-workers 1 closeAndReleaseStagingRepository"

      - name: Prepare release notes
        run: |
          RELEASE_BODY=$(jq -Rs . <<'EOF'
          ${{ github.event.release.body }}
          EOF
          )
          echo "FORMATTED_BODY=${RELEASE_BODY}" >> $GITHUB_ENV

      - name: Send Teams notification
        uses: fjogeleit/http-request-action@v1.16.4
        with:
          url: ${{ secrets.ANDROID_LIBRARIES_TEAMS_WEBHOOK }}
          method: 'POST'
          data: |
            {
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "version": "1.5",
                  "body": [
                    {
                      "type": "ColumnSet",
                      "columns": [
                        {
                          "type": "Column",
                          "width": "auto",
                          "items": [
                            {
                              "type": "Image",
                              "url": "https://raw.githubusercontent.com/Skitionek/notify-microsoft-teams/master/icons/success.png",
                              "width": "56px",
                              "height": "56px",
                              "style": "RoundedCorners"
                            }
                          ]
                        },
                        {
                          "type": "Column",
                          "width": "stretch",
                          "items": [
                            {
                              "type": "TextBlock",
                              "text": "New Mística version published ${{ github.event.release.tag_name }}",
                              "wrap": true,
                              "weight": "Bolder",
                              "style": "heading"
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "type": "TextBlock",
                      "text": ${{ env.FORMATTED_BODY }},
                      "wrap": true
                    },
                    {
                      "type": "ActionSet",
                      "actions": [
                        {
                          "type": "Action.OpenUrl",
                          "title": "Open release",
                          "url": "${{ github.event.release.html_url }}"
                        }
                      ]
                    }
                  ],
                  "$schema": "https://adaptivecards.io/schemas/adaptive-card.json"
                }
              }
            ]
            }