name: "Upload release to MavenCentral"
on:
  release:
    types: [published]
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"

      - name: Build library
        run: 'bash ./gradlew clean :library:assembleRelease :catalog:assembleRelease'

      - name: Release library
        env:
          MOBILE_MAVENCENTRAL_USER: ${{ secrets.MOBILE_MAVENCENTRAL_USER }}
          MOBILE_MAVENCENTRAL_PASSWORD: ${{ secrets.MOBILE_MAVENCENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
        run: "bash ./gradlew :library:publishReleasePublicationToSonatypeRepository -DLIBRARY_VERSION=${{ github.event.release.tag_name }}
          :catalog:publishCatalogPublicationToSonatypeRepository -DLIBRARY_VERSION=${{ github.event.release.tag_name }}
          --max-workers 1 closeAndReleaseStagingRepositories"

      - name: Prepare release notes
        run: |
          RELEASE_BODY=$(jq -Rs . <<'EOF'
          ${{ github.event.release.body }}
          EOF
          )
          echo "FORMATTED_BODY=${RELEASE_BODY}" >> $GITHUB_ENV

      - name: clean Properties file
        run: |
          truncate -s 0 ./app/src/main/res/raw/config.properties
        shell: bash

      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './app/src/main/res/raw/config.properties'
          property: 'APP_VERSION'
          value: '${{ github.event.release.tag_name }}'

      - name: Commit and push new version
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: './app/src/main/res/raw/config.properties'
          message: 'Update app version to ${{ github.event.release.tag_name }}'

      - name: Firebase Publish
        uses: ./.github/actions/firebase-publish
        id: firebase-publish
        with:
          firebase-app-id: '1:413491573542:android:d79e363379e606a7a807e7'
          firebase-json-file: ${{ secrets.FIREBASE_DIST_CREDENTIALS_RC }}
          release-notes: 'Catalog for Mistica Release: ${{ github.event.release.tag_name }}'
          app-icon: 'ic_launcher_rc'
          app-version: '${{ github.event.release.tag_name }}'

      - name: Send Teams notification
        uses: fjogeleit/http-request-action@v1.16.4
        with:
          url: ${{ secrets.ANDROID_LIBRARIES_TEAMS_WEBHOOK }}
          method: 'POST'
          data: |
            {
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "version": "1.5",
                  "body": [
                    {
                      "type": "ColumnSet",
                      "columns": [
                        {
                          "type": "Column",
                          "width": "auto",
                          "items": [
                            {
                              "type": "Image",
                              "url": "https://raw.githubusercontent.com/Skitionek/notify-microsoft-teams/master/icons/success.png",
                              "width": "56px",
                              "height": "56px",
                              "style": "RoundedCorners"
                            }
                          ]
                        },
                        {
                          "type": "Column",
                          "width": "stretch",
                          "items": [
                            {
                              "type": "TextBlock",
                              "text": "New Mística version published ${{ github.event.release.tag_name }}",
                              "wrap": true,
                              "weight": "Bolder",
                              "style": "heading"
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "type": "TextBlock",
                      "text": ${{ env.FORMATTED_BODY }},
                      "wrap": true
                    },
                    {
                      "type": "ActionSet",
                      "actions": [
                        {
                          "type": "Action.OpenUrl",
                          "title": "Open release",
                          "url": "${{ github.event.release.html_url }}"
                        }
                      ]
                    }
                  ],
                  "$schema": "https://adaptivecards.io/schemas/adaptive-card.json"
                }
              }
            ]
            }