name: "Snapshot"
on:
  workflow_dispatch:
    inputs:
      snapshotVersion:
        description: "Snapshot version"
        required: true
jobs:
  firebase-catalog:
    uses: Telefonica/android-shared-workflows/.github/workflows/build-enterprise.yml@firebase
    with:
      build-tasks: 'assembleDebug'
      apk-path: '**/build/outputs/apk/debug/*.apk'
      additional-groups: 'mistica-internal-testers'
      distribution-track: 'internal'
      notify-ci-cd-publication: true
      notify-error-in-publication: true
    secrets: inherit

  debug-firebase-catalog:
    uses: Telefonica/android-shared-workflows/.github/workflows/build-enterprise.yml@firebase
    with:
      build-tasks: 'assembleDebug'
      apk-path: '**/build/outputs/apk/debug/*.apk'
      additional-groups: 'mistica-internal-testers'
      notify-publication-as-pr-comment: true
    secrets: inherit
