name: "Snapshot"
on:
  workflow_dispatch:
    inputs:
      snapshotVersion:
        description: "Snapshot version"
        required: true
jobs:
  firebase-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Telefonica/ios-github-workflows repo
        uses: actions/checkout@v4
        with:
          repository: Telefonica/android-shared-workflows
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .shared-workflows
          ref: firebase

      - name: Build and Upload to Firebase
        uses: ./.shared-workflows/.github/workflows/build-enterprise.yml
        with:
          build-tasks: 'assembleDebug'
          apk-path: '**/build/outputs/apk/debug/*.apk'
          additional-groups: 'mistica-internal-testers'
          distribution-track: 'internal'
          notify-ci-cd-publication: true
          notify-error-in-publication: true