name: "Run tests"
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: "Build Android project"
      run : 'bash ./gradlew clean check assemble'

    - name: Upload Lint results
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: app/build/reports/lint-results-debug.sarif
        category: lint