name: "Run tests"
on:
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: self-hosted-novum
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: "Build Android project"
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: 'bash ./gradlew --no-daemon clean check assemble'
