name: "Run tests"
#on:
#  pull_request:
#    branches:
#      - master
on: 
  workflow_dispatch
jobs:
  tests:
    runs-on: self-hosted-novum
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
        
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Execute tests
      run: 'bash ./gradlew --no-daemon clean check assemble'
