name: "Run tests on mistica builder"
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: self-hosted-novum
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: "Build Android project"
        uses: docker.tuenti.io/android/mistica_builder:2
        with:
          args: 'bash ./gradlew --no-daemon clean check assemble'
