name: "Update screenshot baseline"
on:
  workflow_dispatch:

jobs:
  update_screenshots_baseline:
    uses: Telefonica/android-shared-workflows/.github/workflows/update-baseline.yml@feature/ANDROID-15237-UpdateBaselineShared
    with:
      baseline-update-tasks: 'recordRoborazziDebug'
      emulators-number: 0
      baseline-file-path: './**/screenshots/*'
      commit-message: 'Updated screenshots baseline'
    secrets: inherit
