name: "Update screenshot baseline"
on:
  workflow_dispatch:

jobs:
  update_screenshots_baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check out actions
        uses: actions/checkout@v4
        with:
          repository: Telefonica/android-shared-workflows
          ref: 'feature/ANDROID-15237-UpdateBaselineShared'
          token: "${{ secrets.NOVUM_PRIVATE_REPOS }}"
          path: .github/android-shared-workflows

      - name: "Update screenshot baseline"
        run: |
          # Run the script or workflow from the shared workflows repository
          bash .github/android-shared-workflows/.github/workflows/update-baseline-and-commit.yml \
            --baseline-update-tasks 'recordRoborazziDebug' \
            --emulators-number 0 \
            --baseline-file-path './**/screenshots/*' \
            --commit-message 'Updated screenshots baseline'
